booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'createbooking/', views.CreateBookingView.as_view(),
        name='createbooking'
        ),
    path(
        'managebookings/',
        views.BookingsList.as_view(),
        name='managebookings'),
    path(
        'editbooking/<slug:pk>/',
        views.EditBookingView.as_view(),
        name='editbooking'),
    path(
        'delete/<slug:pk>/',
        views.DeleteBookingView.as_view(),
        name="delete_booking")
]

home/urls.py
from django.urls import path
from home.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home')
    ]

sizzleandsteak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('booking/', include('booking.urls')),
    path('menu/', include('menu.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from django.db import models
from django.contrib.auth.models import User

# Choice fields
CAPACITY = ((2, "2"), (4, "4"), (6, "6"), (8, "8"), (10, "10"), (12, "12"))
BOOKING_TIME = ((1, "12:00pm - 1:45pm"), (2, "2:00pm - 3:45pm"),
                (3, "4:00pm - 5:45pm"), (4, "6:00pm - 7:45pm"))


class Table(models.Model):
    """ Model to create Tables """
    table_number = models.IntegerField(unique=True)
    capacity = models.IntegerField(choices=CAPACITY, default=2)
    wheelchair_accessible = models.BooleanField(default=True)

    class Meta:
        """ Order by table number """
        ordering = ['table_number']

    def __str__(self):
        return str(self.table_number)


class Booking(models.Model):
    """ Model to create a booking """
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="booking_customer")
    booking_name = models.CharField(max_length=25)
    booked_table = models.ForeignKey(
        Table, on_delete=models.CASCADE, related_name="booking_table")
    number_of_guests = models.IntegerField(default=2)
    booking_date = models.DateField()
    booking_time = models.IntegerField(choices=BOOKING_TIME, default=1)

    class Meta:
        """ Order by booking_date and then booking_time """
        ordering = ['booking_date', 'booking_time']

    def __str__(self):
        return str(self.pk)

booking/forms.py
from datetime import datetime
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django import forms
from .models import Booking, Table


class BookingForm(forms.ModelForm):
    """
    Form to create and edit a booking
    """
    class Meta:
        """ Set fields and labels """
        model = Booking
        fields = [
            'booking_name', 'number_of_guests', 'booking_date', 'booking_time'
            ]
        booking_date = forms.DateField(help_text="Date must be a future date")
        labels = {
            'booking_name': 'Name',
            'number_of_guests': 'Number Of Guests',
            'booking_date': 'Date',
            'booking_time': 'Time',
        }

    def clean(self):
        """
        Get form data and clean, check capacity and
        throw errors when tables not available
        """
        date = self.cleaned_data['booking_date']
        time = self.cleaned_data['booking_time']
        guests = self.cleaned_data['number_of_guests']

        table_booked = None

        # Try and get object, as needed for update validation
        # pass error if on create
        try:
            table_booked = Table.objects.get(id=self.instance.booked_table.id)
        except ObjectDoesNotExist:
            pass

        # Filter tables with capacity greater or equal
        # to the number of guests
        bookings_on_requested_date = Booking.objects.filter(
            booking_date=date, booking_time=time)
        # Get bookings on specified date
        tables_with_capacity = list(Table.objects.filter(
            capacity__gte=guests
        ))
        # Iterate over tables not booked to get lowest
        # capacity table
        for booking in bookings_on_requested_date:
            for table in tables_with_capacity:
                if table.table_number == booking.booked_table.table_number:
                    tables_with_capacity.remove(table)
                    break
        # Add booked table to list of tables
        if table_booked is not None:
            if table_booked.capacity >= guests:
                tables_with_capacity.append(table_booked)
        # Throw validation errors on form
        if date < datetime.today().date():
            raise ValidationError(
                'Invalid date - Booking cannot be in the past')
        if table_booked is not None:
            if not tables_with_capacity and table_booked.capacity < guests:
                raise ValidationError(
                    'Sorry, we do not have a table' +
                    ' available for that amount of guests'
                )
        if not tables_with_capacity:
            raise ValidationError('No tables available for this date and time')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['booking_date'].widget.attrs['class'] = 'datepicker'
        self.fields['booking_date'].widget.attrs['autocomplete'] = 'off'

booking/views.py
from datetime import timedelta, date
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView, CreateView, UpdateView, ListView
from django.contrib import messages
from .models import Booking, Table
from .forms import BookingForm


class CreateBookingView(LoginRequiredMixin, CreateView):
    """
    View to render createbookings
    and allow user to create a booking
    """
    form_class = BookingForm
    template_name = 'booking/booking.html'
    success_url = "/booking/managebookings/"
    model = Booking

    def form_valid(self, form):
        """
        Before form submission, assign table with lowest capacity
        needed for booking guests
        """
        form.instance.customer = self.request.user
        date = form.cleaned_data['booking_date']
        time = form.cleaned_data['booking_time']
        guests = form.cleaned_data['number_of_guests']
        # Filter tables with capacity greater or equal
        # to the number of guests
        tables_with_capacity = list(Table.objects.filter(
            capacity__gte=guests
        ))
        # Get bookings on specified date
        bookings_on_requested_date = Booking.objects.filter(
            booking_date=date, booking_time=time)
        # Iterate over bookings to get tables not booked
        for booking in bookings_on_requested_date:
            for table in tables_with_capacity:
                if table.table_number == booking.booked_table.table_number:
                    tables_with_capacity.remove(table)
                    break
        # Iterate over tables not booked to get lowest
        # capacity table to assign to booking
        lowest_capacity_table = tables_with_capacity[0]
        for table in tables_with_capacity:
            if table.capacity < lowest_capacity_table.capacity:
                lowest_capacity_table = table
        form.instance.booked_table = lowest_capacity_table

        messages.success(
            self.request,
            f'Booking confirmed for {guests} guests on {date}'
        )

        return super(CreateBookingView, self).form_valid(form)


class BookingsList(LoginRequiredMixin, ListView):
    """
    View to render ManageBookings
    """
    model = Booking
    template_name = 'booking/managebookings.html'

    def get_queryset(self):
        """ Queryset function for manage booking search """
        query = self.request.GET.get('q')
        dates = self.request.GET.get('d')
        if query:
            return Booking.objects.filter(id=query)
        if dates:
            return Booking.objects.filter(booking_date=dates)
        if self.request.user.is_staff:
            # returns all bookings with date greater than yesterday
            return Booking.objects.filter(
                booking_date__gt=(date.today()-timedelta(days=1))
                )
        else:
            # returns all bookings for logged in customer
            # with date greater than yesterday
            return Booking.objects.filter(
                customer=self.request.user,
                booking_date__gt=(date.today()-timedelta(days=1))
                )


class EditBookingView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    A view to provide a Form to the user
    to edit a booking
    """
    form_class = BookingForm
    template_name = 'booking/edit_booking.html'
    success_url = "/booking/managebookings"
    model = Booking

    def form_valid(self, form):
        """
        Before form submission, run capacity checks and
        assign to table with lowest capacity
        """
        date = form.cleaned_data['booking_date']
        time = form.cleaned_data['booking_time']
        guests = form.cleaned_data['number_of_guests']

        # Filter tables with capacity greater or equal
        # to the number of guests
        tables_with_capacity = list(Table.objects.filter(
            capacity__gte=guests
        ))
        # Get bookings on specified date
        bookings_on_requested_date = Booking.objects.filter(
            booking_date=date, booking_time=time)
        # Iterate over bookings and remove table from bookings
        # with capacity
        for booking in bookings_on_requested_date:
            for table in tables_with_capacity:
                if table.table_number == booking.booked_table.table_number:
                    tables_with_capacity.remove(table)
                    break
        # Iterate over tables with capacity and assign lowest
        # capacity table
        if tables_with_capacity:
            lowest_capacity_table = tables_with_capacity[0]
            for table in tables_with_capacity:
                if table.capacity < lowest_capacity_table.capacity:
                    lowest_capacity_table = table
            form.instance.booked_table = lowest_capacity_table

        messages.success(
            self.request,
            f'Successfully updated booking for {guests} guests on {date}'
        )
        return super(EditBookingView, self).form_valid(form)

    def test_func(self):
        """ Test user is staff or throw 403 """
        if self.request.user.is_staff:
            return True
        else:
            return self.request.user == self.get_object().customer


class DeleteBookingView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """ A view to delete a booking """
    model = Booking
    success_url = "/booking/managebookings"

    def form_valid(self, form):
        """ Display toast message on form success """
        messages.success(
            self.request,
            'Successfully deleted booking'
        )
        return super(DeleteBookingView, self).form_valid(form)

    def test_func(self):
        """ Test user is staff else throw 403 """
        if self.request.user.is_staff:
            return True
        else:
            return self.request.user == self.get_object().customer

booking/templates/booking/booking.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'booking/css/datepicker.css' %}">
{% endblock %}

<!-- Create booking form -->
{% block content %}
<div class="m-3">
    <form method="POST" action="{% url 'createbooking' %}" class="form mb-2 p-2 form-style" enctype="multipart/form-data">
        <h1 class="text-center">Create Booking</h1>
        {% csrf_token %}
        {{ form|crispy }}
        {{ form.media }}
        <button type="submit" class="btn form-style">Create</button>
    </form>
</div>

{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
    $('.datepicker').datepicker();
</script>
{% endblock %}

booking/templates/booking/booking_confirm_delete.html
{% extends 'base.html' %}
{{ form.media }}

{% block content %}

<!-- Booking confirm delete form -->
<div class="form-style text-center p-3 m-3">
    <h1 class="text-center">Confirm Booking Deletion</h1>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete Booking: "{{ object.pk }}"?</p>
        <p>Name: {{ object.booking_name }}</p>
        <p>Table: {{ object.booked_table }}</p>
        <p>Date: {{ object.booking_date }}</p>
        <p>Time: {{ object.get_booking_time_display }}</p>

        <input type="submit" value="Confirm" class="btn button-style">
    </form>
</div>
{% endblock %}

booking/templates/booking/edit_booking.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'booking/css/datepicker.css' %}">
{% endblock %}

{% block content %}

<!-- Edit booking form -->
<div class="m-3">
    <form method="POST" action="{% url 'editbooking' booking.id %}" class="form mb-2 p-2 form-style" enctype="multipart/form-data">
        <h1 class="text-center">Edit Booking</h1>
        {% csrf_token %}
        {{ form.id }}
        {{ form|crispy }}
        {{ form.media }}
        <button type="submit" class="btn button-style">Create</button>
    </form>
</div>

{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
    // Initialize datepicker
    $('.datepicker').datepicker();
</script>
{% endblock %}

booking/templates/booking/managebookings.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'booking/css/booking.css' %}">
{% endblock %}

{% block content %}

<div class="container m-3">
    <!-- Search querys -->
    {% if request.user.is_staff %}
        <form method='GET' class="mb-3">
            <input type='text' name='q' value='{{ request.GET.q }}' autocomplete="off" aria-label="Search Booking by reference"
                placeholder="Search Booking Ref">
            <button class="btn p-0 search-btn" type='submit' value="Search Booking by ref" aria-label="Click to search by booking ref">
                <i class="fas fa-search"></i>
            </button>
        </form>
        <form method='GET' class="mb-3">
            <input type='text' name='d' value='{{ request.GET.d }}' class="datepicker" autocomplete="off" aria-label="Search Bookings by date"
                placeholder="Search Booking Date">
            <button class="btn p-0 search-btn" type='submit' value="Search Booking by ref" aria-label="Click to search by date">
                <i class="fas fa-search"></i>
            </button>
        </form>
    {% endif %}
    <!-- Manage bookings table -->
    <div class="form-style">
        <h1 class="text-center">Bookings List</h1>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Booking Reference</th>
                    <th>Customer</th>
                    <th>Date</th>
                    <th>Time Slot</th>
                    <th>No. Guests</th>
                    {% if user.is_staff %}
                    <th>Table:</th>
                    <th>Capacity:</th>
                    {% endif %}
                    <th><span class="sr-only">Edit Button Column</span></th>
                    <th><span class="sr-only">Delete Button Column</span></th>
                </tr>
            </thead>
            {% for booking in object_list %}
            <tbody>
                <tr>
                    <td>
                        {{ booking.pk }}
                    </td>
                    <td>
                        {{ booking.booking_name }}
                    </td>
                    <td>
                        {{ booking.booking_date }}
                    </td>
                    <td>
                        {{ booking.get_booking_time_display }}
                    </td>
                    <td>
                        {{ booking.number_of_guests }}
                    </td>
                    {% if user.is_staff %}
                    <td>
                        {{ booking.booked_table }}
                    </td>
                    <td>
                        {{ booking.booked_table.capacity }}
                    </td>
                    {% endif %}
                    <td>
                        <a href="{% url 'editbooking' booking.id %}" class="btn button-style m-2">Edit</a>
                    </td>
                    <td>
                        <a href="{% url 'delete_booking' booking.id %}" class="btn button-style m-2">Delete</a>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</div>

{%endblock%}
{% block extra_js %}
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
    $('.datepicker').datepicker({
        dateFormat: 'yy-mm-dd',
    });
</script>
{% endblock %}